"""empty message

Revision ID: 147610cf8c8
Revises: 20213e1d67f7
Create Date: 2015-05-05 22:24:16.468311

"""

# revision identifiers, used by Alembic.
revision = '147610cf8c8'
down_revision = '20213e1d67f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
