"""empty message

Revision ID: 159cfd4787a
Revises: 39164ffca08a
Create Date: 2015-05-03 21:33:23.776359

"""

# revision identifiers, used by Alembic.
revision = '159cfd4787a'
down_revision = '39164ffca08a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
