"""empty message

Revision ID: 19ca60357b03
Revises: 54e7b9eeece8
Create Date: 2015-05-05 23:39:47.486599

"""

# revision identifiers, used by Alembic.
revision = '19ca60357b03'
down_revision = '54e7b9eeece8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
