"""empty message

Revision ID: 20213e1d67f7
Revises: 159cfd4787a
Create Date: 2015-05-05 22:18:51.187484

"""

# revision identifiers, used by Alembic.
revision = '20213e1d67f7'
down_revision = '159cfd4787a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('social_id', sa.String(length=250), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.drop_column('user', 'social_id')
    op.drop_column('user', 'name')
    ### end Alembic commands ###
