"""empty message

Revision ID: 2190b5348c5f
Revises: 6f6b8eebb2b
Create Date: 2015-05-06 00:09:44.212171

"""

# revision identifiers, used by Alembic.
revision = '2190b5348c5f'
down_revision = '6f6b8eebb2b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('administrator', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    op.drop_table('user')
    op.drop_constraint(u'todo_owner_id_fkey', 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'client_user', ['owner_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(u'todo_owner_id_fkey', 'todo', 'user', ['owner_id'], ['id'])
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('social_id', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('administrator', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'user_pkey')
    )
    op.drop_table('client_user')
    ### end Alembic commands ###
