"""empty message

Revision ID: 271d1e823954
Revises: 147610cf8c8
Create Date: 2015-05-05 23:15:59.765091

"""

# revision identifiers, used by Alembic.
revision = '271d1e823954'
down_revision = '147610cf8c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
