"""empty message

Revision ID: 27311dc6c4c2
Revises: 4860a48509e5
Create Date: 2015-03-20 05:29:55.868707

"""

# revision identifiers, used by Alembic.
revision = '27311dc6c4c2'
down_revision = '4860a48509e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('image', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'image')
    ### end Alembic commands ###
