"""empty message

Revision ID: 280948e13980
Revises: 27311dc6c4c2
Create Date: 2015-05-03 16:03:57.982925

"""

# revision identifiers, used by Alembic.
revision = '280948e13980'
down_revision = '27311dc6c4c2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('project')
    op.add_column('todo', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'todo_project_id_fkey', 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'todo', ['parent_id'], ['id'])
    op.drop_column('todo', 'project_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(u'todo_project_id_fkey', 'todo', 'project', ['project_id'], ['id'])
    op.drop_column('todo', 'parent_id')
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'project_pkey')
    )
    op.drop_table('user')
    ### end Alembic commands ###
