"""empty message

Revision ID: 2bfb27428c5d
Revises: 19ca60357b03
Create Date: 2015-05-05 23:42:59.986602

"""

# revision identifiers, used by Alembic.
revision = '2bfb27428c5d'
down_revision = '19ca60357b03'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
