"""empty message

Revision ID: 320900cd94f5
Revises: 393dc7ea67f4
Create Date: 2015-05-03 18:23:46.849183

"""

# revision identifiers, used by Alembic.
revision = '320900cd94f5'
down_revision = '393dc7ea67f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
