"""empty message

Revision ID: 36f0608ba77c
Revises: 24480426012d
Create Date: 2015-03-19 05:18:47.275577

"""

# revision identifiers, used by Alembic.
revision = '36f0608ba77c'
down_revision = '24480426012d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'project', ['project_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'project_id')
    ### end Alembic commands ###
