"""empty message

Revision ID: 393dc7ea67f4
Revises: 45cd65081a43
Create Date: 2015-05-03 18:20:59.144653

"""

# revision identifiers, used by Alembic.
revision = '393dc7ea67f4'
down_revision = '45cd65081a43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'user', ['owner_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'owner_id')
    ### end Alembic commands ###
