"""empty message

Revision ID: 45cd65081a43
Revises: 458f3a75928a
Create Date: 2015-05-03 18:16:36.896142

"""

# revision identifiers, used by Alembic.
revision = '45cd65081a43'
down_revision = '458f3a75928a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todo', 'user', ['owner_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'owner_id')
    ### end Alembic commands ###
