"""empty message

Revision ID: 4860a48509e5
Revises: bd00ab7c709
Create Date: 2015-03-20 04:53:14.756574

"""

# revision identifiers, used by Alembic.
revision = '4860a48509e5'
down_revision = 'bd00ab7c709'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image')
    ### end Alembic commands ###
