"""empty message

Revision ID: 54e7b9eeece8
Revises: 271d1e823954
Create Date: 2015-05-05 23:38:35.230802

"""

# revision identifiers, used by Alembic.
revision = '54e7b9eeece8'
down_revision = '271d1e823954'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
