"""empty message

Revision ID: 5962d0ef185c
Revises: 2bfb27428c5d
Create Date: 2015-05-05 23:44:23.101663

"""

# revision identifiers, used by Alembic.
revision = '5962d0ef185c'
down_revision = '2bfb27428c5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['social_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    ### end Alembic commands ###
