"""empty message

Revision ID: 6f6b8eebb2b
Revises: 5962d0ef185c
Create Date: 2015-05-05 23:58:11.806657

"""

# revision identifiers, used by Alembic.
revision = '6f6b8eebb2b'
down_revision = '5962d0ef185c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('administrator', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'administrator')
    ### end Alembic commands ###
