"""empty message

Revision ID: bd00ab7c709
Revises: 36f0608ba77c
Create Date: 2015-03-19 22:55:24.412100

"""

# revision identifiers, used by Alembic.
revision = 'bd00ab7c709'
down_revision = '36f0608ba77c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
