"""empty message

Revision ID: c3c21c020e7
Revises: 320900cd94f5
Create Date: 2015-05-03 18:24:51.007463

"""

# revision identifiers, used by Alembic.
revision = 'c3c21c020e7'
down_revision = '320900cd94f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
